---
test:
  name: DatasetBidRegistry Benchmark - Geth POW
  description: Benchmark for DatasetBidRegistry Ethereum Smart Contract
  workers:
    type: local
    number: 1
  rounds:
    #---------------------------------------------------------------Register increasing send rate:---------------------------------------------------------------
    - label: Register 100tx @ 10 TPS
      contractId: DatasetBidRegistry
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts: { tps: 10 }
      workload:
        module: benchmarks/workloads/register.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    - label: Register 100tx @ 50 TPS
      contractId: DatasetBidRegistry
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts: { tps: 50 }
      workload:
        module: benchmarks/workloads/register.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    - label: Register 100tx @ 100 TPS
      contractId: DatasetBidRegistry
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: benchmarks/workloads/register.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    #---------------------------------------------------------------Offer increasing send rate:---------------------------------------------------------------

    - label: Offer 100tx @ 10 TPS
      contractId: DatasetBidRegistry
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts: { tps: 10 }
      workload:
        module: benchmarks/workloads/offer.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    - label: Offer 100tx @ 50 TPS
      contractId: DatasetBidRegistry
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts: { tps: 50 }
      workload:
        module: benchmarks/workloads/offer.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    - label: Offer 100tx @ 100 TPS
      contractId: DatasetBidRegistry
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: benchmarks/workloads/offer.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    #---------------------------------------------------------------Register increasing number of transactions:---------------------------------------------------------------
    - label: Register 100tx @ 100 TPS
      contractId: DatasetBidRegistry
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: benchmarks/workloads/register.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    - label: Register 500tx @ 100 TPS
      contractId: DatasetBidRegistry
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: benchmarks/workloads/register.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    - label: Register 1000tx @ 100 TPS
      contractId: DatasetBidRegistry
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: benchmarks/workloads/register.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

    #---------------------------------------------------------------Offer increasing number of transactions:---------------------------------------------------------------
    - label: Offer 100tx @ 100 TPS
      contractId: DatasetBidRegistry
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: benchmarks/workloads/offer.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1
    - label: Offer 500tx @ 100 TPS
      contractId: DatasetBidRegistry
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: benchmarks/workloads/offer.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1
    - label: Offer 1000tx @ 100 TPS
      contractId: DatasetBidRegistry
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: benchmarks/workloads/offer.js
        arguments:
          contractId: DatasetBidRegistry
          contractVersion: 0.0.1

monitors:
  resource:
    - module: process
      options:
        interval: 3
        processes:
          [{ command: "node", arguments: "caliper.js", multiOutput: "avg" }]
      charting:
        bar:
          metrics: [all]
